services:
  funchive-config-server:
    ports:
      - "8888:8888"
    volumes:
      - ./funchive-config-server:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  funchive-discovery-server:
    ports:
      - "8761:8761"
    volumes:
      - ./funchive-discovery-server:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  funchive-user-service:
    ports:
      - "8081:8080"
    volumes:
      - ./funchive-user-service:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  funchive-function-service:
    ports:
      - "8082:8080"
    volumes:
      - ./funchive-function-service:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  funchive-gateway-server:
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  funchive-web:
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080
    volumes:
      - ./funchive-web:/app
