services:
  docker-dind:
    ports:
      - "2375:2375"  # Expose Docker daemon for local development
      - "2376:2376"  # Expose Docker TLS daemon
    environment:
      - DOCKER_TLS_CERTDIR=  # Disable TLS for development

  kafka:
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  funchive-config-server:
    ports:
      - "8888:8888"
    volumes:
      - ./funchive-config-server:/app
    environment:
      - SPRING_PROFILES_ACTIVE=native

  funchive-discovery-server:
    ports:
      - "8761:8761"
    volumes:
      - ./funchive-discovery-server:/app
    environment:
      - SPRING_PROFILES_ACTIVE=native

  funchive-user-service:
    ports:
      - "8081:8080"
    volumes:
      - ./funchive-user-service:/app
    environment:
      - SPRING_PROFILES_ACTIVE=native

  funchive-function-service:
    ports:
      - "8082:8080"
    volumes:
      - ./funchive-function-service:/app
    environment:
      - SPRING_PROFILES_ACTIVE=native

  funchive-sandbox-service:
    ports:
      - "8083:8080"
    volumes:
      - ./funchive-sandbox-service:/app
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - DOCKER_HOST=tcp://docker-dind:2375  # Override for containerized development

  funchive-gateway-server:
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=native

  funchive-web:
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080
    volumes:
      - ./funchive-web:/app
