services:
  funchive-auth-server:
    image: openjdk:24-jdk-slim
    working_dir: /app/funchive-auth-server
    command: ["./mvnw", "clean", "spring-boot:run"]
    ports:
      - "${FUNCHIVE_AUTH_SERVER_PORT}:9000"
    volumes:
      - ./auth-server:/app/funchive-auth-server
      - maven-cache:/root/.m2

  funchive-auth-postgres:
    ports:
      - "${FUNCHIVE_AUTH_POSTGRES_PORT}:5432"
      
  funchive-config-server:
    image: openjdk:24-jdk-slim
    working_dir: /app/funchive-config-server
    command: ["./mvnw", "clean", "spring-boot:run"]
    ports:
      - "${FUNCHIVE_CONFIG_SERVER_PORT}:8888"
    volumes:
      - ./config-repo:/app/funchive-config-repo
      - ./config-server:/app/funchive-config-server
      - maven-cache:/root/.m2

  funchive-discovery-server:
    image: openjdk:24-jdk-slim
    working_dir: /app/funchive-discovery-server
    command: ["./mvnw", "clean", "spring-boot:run"]
    ports:
      - "${FUNCHIVE_DISCOVERY_SERVER_PORT}:8761"
    volumes:
      - ./gateway-server:/app/funchive-discovery-server
      - maven-cache:/root/.m2

  funchive-gateway-server:
    image: openjdk:24-jdk-slim
    working_dir: /app/funchive-gateway-server
    command: [ "./mvnw", "clean", "spring-boot:run" ]
    ports:
      - "${GATEWAY_SERVER_PORT}:8080"
    volumes:
      - ./gateway-server:/app/funchive-gateway-server
      - maven-cache:/root/.m2

  funchive-function-service:
    image: openjdk:24-jdk-slim
    working_dir: /app/funchive-function-service
    command: ["./mvnw", "clean", "spring-boot:run"]
    ports:
      - "${FUNCHIVE_FUNCTION_SERVICE_PORT}:8080"
    volumes:
      - ./function-service:/app/funchive-function-service
      - maven-cache:/root/.m2

  funchive-function-mongo:
    ports:
      - "${FUNCHIVE_FUNCTION_MONGO_PORT}:27017"

  funchive-sandbox-service:
    image: openjdk:24-jdk-slim
    working_dir: /app/funchive-sandbox-service
    command: [ "./mvnw", "clean", "spring-boot:run" ]
    ports:
      - "${FUNCHIVE_SANDBOX_SERVICE_PORT}:8080"
    volumes:
      - ./sandbox-service:/app/funchive-sandbox-service
      - maven-cache:/root/.m2

  funchive-storage-service:
    image: openjdk:24-jdk-slim
    working_dir: /app/funchive-storage-service
    command: ["./mvnw", "clean", "spring-boot:run"]
    ports:
      - "${FUNCHIVE_STORAGE_SERVICE_PORT}:8080"
    volumes:
      - ./storage-service:/app/funchive-storage-service
      - maven-cache:/root/.m2

  funchive-storage-mongo:
    ports:
      - "${FUNCHIVE_STORAGE_MONGO_PORT}:27017"

  funchive-web:
    image: node:18-alpine
    working_dir: /app/funchive-web
    command: ["npm", "start"]
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./web:/app/funchive-web
      - npm-cache:/root/.npm

networks:
  funchive-network:
    driver: bridge
    name: funchive-network

volumes:
  maven-cache:
    driver: local
  npm-cache:
    driver: local
